{% set name = "pyramid" %}
{% set version = "1.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  # when updating to 2.0, make sure to add "python >=3.4" to "host" and "run" sections
  # because 2.0 no longer supports Python 2

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe1bd1140e6b79fe07f0053981d49be2dc66656cc8b481dd7ffcaa872fc25467

build:
  noarch: python
  number: 0
  entry_points:
    - pcreate=pyramid.scripts.pcreate:main
    - pserve=pyramid.scripts.pserve:main
    - pshell=pyramid.scripts.pshell:main
    - proutes=pyramid.scripts.proutes:main
    - pviews=pyramid.scripts.pviews:main
    - ptweens=pyramid.scripts.ptweens:main
    - prequest=pyramid.scripts.prequest:main
    - pdistreport=pyramid.scripts.pdistreport:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - hupper >=1.5
    - plaster
    - plaster_pastedeploy
    - python
    - translationstring >=0.4
    - venusian >=1.0
    - webob >=1.8.3
    - zope.deprecation >=3.5.0
    - zope.interface >=3.8.0

test:
  imports:
    - pyramid
    - pyramid.config
    - pyramid.scaffolds
    - pyramid.scripts
  commands:
    - pcreate --help
    - pserve --help
    - pshell --help
    - proutes --help
    - pviews --help
    - ptweens --help
    - prequest --help
    - pdistreport --help
  requires:
    - webtest >=1.3.1
    # Dependency not required for running test imports and commands
    # - zope.component >=4.0

about:
  home: https://trypyramid.com
  license: BSD-derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Pyramid Web Framework, a Pylons project
  doc_url: https://docs.pylonsproject.org/projects/pyramid/
  dev_url: https://github.com/Pylons/pyramid

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
